### ISSUE TITLE
the filter should only load javascript when enabled

### ISSUE THREAD

**Issue by ewallah** [justinhunt/moodle-filter_generico#1]
The generico filter is loading javascripts in case it will be needed, not when it is needed. Even if you completely disable the filter on site level, all pages load javascript that will never be used. In low bandwidth environments this can be an issue. 

But there is also a security aspect: if an administrator disables a plugin on site level, he/she cannot be 100% sure the javascript code will never be executed. If a plugin is disabled, it should not initialize.

**Comment by justinhunt** [comment]
This may have been an issue in early versions of Generico, but in recent versions it loads javascript according to standard Moodle plugin practices
