### ISSUE TITLE
Generico rendering all snippets in Italics

### ISSUE THREAD

**Issue by EricJLange** [justinhunt/moodle-filter_generico#11]
I'm just implementing Generico for the first time, and have created a very simple template with just a couple of variables. 

For some reason, all the code is being encapsulated inside of <i>italics</i> tags. This is true even if I remove all variables and just use text and HTML in my template.

Is this by design?

**Comment by EricJLange** [comment]
Well, I'll answer my own silly question :)

It turns out, because I was copying the Generico example from the documentation, the italics that the docs were written in were auto-formatting when pasted into the Atto editor. I went into HTML edit mode and stripped out the italics tags.

That's embarrassing, but I'll own it. Thanks for the great plugin!

**Comment by justinhunt** [comment]
Ha, ha but at least you are honest! 
Thanks for following up on it. It just goes to show, that if you leave an issue unanswered long enough , it will answer itself.
