### ISSUE TITLE
Generico tabbs template: showing tabs as bullets. 

### ISSUE THREAD

**Issue by talicharlotte** [justinhunt/moodle-filter_generico#15]
This is a simple one, but it took me a while to figure it out, because I was looking for a complicated answer. The tabb templete that comes with generico Release 1.3.12, has no styling applied. I was just about to make a new template for tabs when I noticed the following in the CSS temlate link: 
/cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css. 

Only one /. 
Changed it to:
//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css 

and now all is well.

**Comment by justinhunt** [comment]
Thanks Charlotte. Looks like I better fix that one up!

**Comment by justinhunt** [comment]
Charlotte, I finally fixed that. Sorry it just slipped beneath the fold and got lost. Thanks again for reporting it.
