### ISSUE TITLE
Critical Security issue

### ISSUE THREAD

**Issue by GraceAshton89** [justinhunt/moodle-filter_generico#17]
Hello,

I've identified a critical security issue with this plugin which I would like to privately disclose but I cannot find a way to make this issue Private, nor to message privately, is there a way I can get in contact?

Regards,
Grace

**Comment by justinhunt** [comment]
Hi Grace. 
Thanks for finding it and keeping it quiet.

Can you send visit https://poodll.com/contact and leave a message there? Then I will reply by email.

Thanks

**Comment by justinhunt** [comment]
This was fixed in https://github.com/justinhunt/moodle-filter_generico/commit/1ba5e9f7362df4059e0986706a5480f72bea3b65#diff-5bbd3ccd25214f9956eea7e9f714bc08
