### ISSUE TITLE
commented line in generico_presets_amd.js breaks grunt

### ISSUE THREAD

**Issue by ewallah** [justinhunt/moodle-filter_generico#2]
filter/generico/amd/src/generico_presets_amd.js
89 // controls['jquery'].checked = (presetdata[presetindex]['jquery'] && presetdata[presetindex]['jquery']!='0') ? true : false;
^ Line is too long.

filter/videoeasy/amd/src/videoeasy_presets_amd.js
86 // controls['jquery'].checked = (presetdata[presetindex]['jquery'] && presetdata[presetindex]['jquery']!='0') ? true : false;
^ Line is too long.

>> 2 errors in 37 files
Warning: Task "jshint:amd" failed. Use --force to continue.

When I remove the commented lines, my grunt command works again like it should.

**Comment by justinhunt** [comment]
OK. I have done this. Thanks for the fix.

**Comment by ewallah** [comment]
THX
