### ISSUE TITLE
Generico Tabs and Bullet Points not working properly

### ISSUE THREAD

**Issue by krendlV** [justinhunt/moodle-filter_generico#23]
Generico Plugin Version 1.4.10(Build 2019071300)

Hello Justin, 
Valentin from FH-Technikum in Austria here.
I have found the Generico-Plugin recently and like it alot.

When using the Generico Tabs and using a Bullet-Point List (unordered List in Atto) the Tab Items are shown in the List. I attached a Picture with the problem.
![Tabs Error bullet point](https://user-images.githubusercontent.com/59736069/72159837-887dc200-33bd-11ea-8a15-f70a05f16f1f.GIF)

Is there a way to fix this?

Thank you very much
Valentin

**Comment by krendlV** [comment]
Already Known

**Comment by justinhunt** [comment]
Thanks for the report. Yes its a tricky one. I am sure it can be solved. But its probably easier just to use asterisks or non-html-bullets.
