### ISSUE TITLE
Unable to delete a template

### ISSUE THREAD

**Issue by nadavkav** [justinhunt/moodle-filter_generico#28]
How do I delete a template in the middle of the list?

**Comment by justinhunt** [comment]
Hi Nadav. It's a bit naff, but you just choose "blank" from the list of presets on the template's settings page. that will clear all the fields.  Then save it. That will reset the template to its initial state. But it will still be in the middle of the list as a blank template. So next time you make a template you would choose that one.

As we discussed once, the templates should really be in a database not in the settings system.  But perhaps we can fix up that list page at least so they are in alphabetical or sortable order

**Comment by nadavkav** [comment]
Hi Justin, thank you for the quick reply!
And for reminding me this hack for resetting a template.
I now remembered we discussed it a log time ago.

For now, It's a good enough solution for us.
Don't waste precious time improving it, only for us.
