### ISSUE TITLE
multi-line html being stripped

### ISSUE THREAD

**Issue by whanrott** [justinhunt/moodle-filter_generico#3]
I've defined a simple info box which encloses html split across more than one line. The lines are enclosed in <p> tags. The template renders these to \r\n in the output.

Is there a workaround for this? Is there a plan to support multi-line content?

**Comment by justinhunt** [comment]
Can you download the template "bundle" from the green button on the template page and post it here?

But I will take a punt at what might be the issue.

If the text is set as variables to the template, then what you are doing won't work very well. 
If the text is sandwiched between the Generico open and close filter strings, I would not expect this problem to occur. There is a field in the template settings to set an end tag. Usually this would contain a </div>, to close a <div> that was in the template's body field. On the page where you use the template, the close filter string has the suffix _end in the type declaration.
So a page with such a filter string might look like:
{GENERICO:type=simpleinfobox}
Blah blah blah
yada yada yada
bu bu bu
{GENERICO:type=simpleinfobox_end}

**Comment by whanrott** [comment]
Hi Justin,

I think that the enclosed tags are what I was looking for. I had just misunderstood how to use them.

Thanks
Will
