### ISSUE TITLE
Recent version breaks Atto Editor in Calendar

### ISSUE THREAD

**Issue by mattgig** [justinhunt/moodle-filter_generico#30]
The new Generico version seems to break the Atto Editor in the Calendar in Moodle 3.11.6 when the Generico(Atto) plugin is used. The place where the editor should show up remains empty. Therefore it is not possible to give further information for an event.
When you remove Generico from the Atto editor the Calendar works again.

**Comment by justinhunt** [comment]
Thanks for the report. Can you be more clear about where the Atto editor is broken? 
I do not know where the atto editor in the calendar is. And do you mean the entire Atto editor fails to load?

**Comment by mattgig** [comment]
When you include the Generico Icon in the Atto Editor, the Atto editor no longer appears in the Calendar. Thus, you are not able to provide any details about the entry in the calendar.

![image](https://user-images.githubusercontent.com/7272764/161117344-109f47e7-a61a-4000-a7fe-c2958a16508f.png)

As soon as you remove the Icon the calendar form works properly again.

![image](https://user-images.githubusercontent.com/7272764/161117580-a67154d0-d9d7-45fb-9f24-ccd2fee05460.png)

The problem is very likely related to the latest update of the Generico filter as I have a second installation with the same Moodle version but without the Generico update, and there editing details in the calendar still works as expected.

In the browser console I get the following error with the new version of Generico:

![image](https://user-images.githubusercontent.com/7272764/161119010-dde801db-444d-4caa-be41-7c3a495c6469.png)

In case you need some additional details, please let me know than I will try to dig some deeper.

And thanks for a great plugin which makes writing Moodle courses a lot easier.
Matthias

**Comment by mattgig** [comment]
Hi Justin

Thanks for getting back to me.

I did some further testing and installed the new Generico filter version on my other installation:
The error doesn't appear there, so as you said, it must be some local interaction.

In my other installation is strangely only appears when the generico Atto editor plugin is active (even if it is the only plugin in the Atto editor and all the other plugins don't cause such a problem).

I also checked your suggestion: 
1) The Generico filter and the Atto editor plugin are at the right place.
2) There are no PHP errors
3) In the Console I get this error when diving deeper:

![image](https://user-images.githubusercontent.com/7272764/161321603-d8f65023-80ce-48fb-84c6-165448c73345.png)

In case you have an idea what further steps I could take to find the problem, I'm open to suggestion. But as it is definitely a local problem, please don't waste any more time on it. I will use other channels to find out what's going on. And in case I find the problem, I will report back to you.

**Comment by justinhunt** [comment]
Its a bit of a mystery. I guess you tried purging your moodle cache. If not please try that.

If the Generico code is corrupt perhaps you could remove the generico folder and re clone. Or just reset the repo with: git reset --hard HEAD 

Its also possible that somewhere you are using a Generico template, and that template is messed up. eg it has not closed a tag, or has unclosed quote. And on the page you load the calendar, that template is being called. If you disable the Generico filter but leave the Generico Icon on Atto, does it load? [this seems not that likely to me]

There is a feature in Generico Atto plugin where a replacement icon can be uploaded, because a big gray "G" indicated something else in France(?), and it was requested. Are you using that feature? If so remove the uploaded file and retest.

**Comment by mattgig** [comment]
I tried your suggestions (thanks again for your time):

1) Cache has been purged repeatedly (and before). Problems persists.
2) Disabled the Generico filter. Problem persists, but probably proves that the problem is not caused by the filter itself.
3) I copied the Generico plugins (filter and Atto) over from the working installation to make sure, there is no code corruption. Problems persists.
4) I use the standard icon in both installations.

I therefore guess it must be some weird interaction with some recent changes in the code of a plugin or Moodle core because the only difference between the two installations are the number of additional plugins installed (Generico plugins are now the same as it the Moodle code basis).

I will continue searching but this will probably take some time. In case I find the source of the problem, I'll let you know.

**Comment by mattgig** [comment]
I think I have finally found the issue with caused the problem in my installation:

In some of the templates I use I have put some javascript into the body of the template which normally doesn't cause any problem. However, in at least one cause, the code has probably spilled over and caused a number of strange behaviours such as the reported one.

I don't know whether this is a common occurance or I was just unlucky.

**Comment by justinhunt** [comment]
OK. Good sleuthing. JS code in the body of the template is usually fine, though I am not sure if jquery will be available. AMD modules wont work there either. And if somehow that template was expanded inside another script tag ... that would break something. I am not sure how that would happen though.
