### ISSUE TITLE
Feature request: support for course custom fields

### ISSUE THREAD

**Issue by SamirSaidani** [justinhunt/moodle-filter_generico#31]
Hi,

Thanks a lot for this awesome plugin: it's saving me a lot of time !

It would be really nice to add course custom fields the same way you did for custom profile fields.

For instance:
`Duration of the course: @@COURSE:duration@@`

Thanks :-)
S.

**Comment by justinhunt** [comment]
Thanks for reporting this @SamirSaidani it should be fixed now
