### ISSUE TITLE
Access course custom field data from Generico

### ISSUE THREAD

**Issue by a-kempka** [justinhunt/moodle-filter_generico#36]
Your plugin is a real timesaver!

Is there any way to access a custom course field from within generico?

**Comment by justinhunt** [comment]
You know I thought this was working. And I see another used also posted about this earlier this year and I missed it.

You should be able to use @@COURSE:[custom field short name]@@
So if the custom field name is "icecream" ..
@@COURSE:icecream@@

But I just tested it now. And there is a little bug. If the courseid is not passed in, it fails. I will fix that over the next day or two.
In the meantime if you want to test it, try passing in the courseid. 
eg {GENERICO:type=coursefieldtest,courseid=2} then the custom fields in the template should resolve

**Comment by justinhunt** [comment]
This should be fixed now. Thanks for reporting it

**Comment by a-kempka** [comment]
Thanks for fixing the issue with the missing course ID in conjunction with the course fields. Custom course fields work nicely now. 

We implemented custom course fields for exam courses that contain an exam and additional informations. Generico is used for displaying infos when the exams will take place etc.
This enables us to create courses in bulk via a CSV-file (and a template course) and to populate custom fields (such as exam date) with the CSV. This is a real time saver.
