### ISSUE TITLE
User profile variables - Custom profile field not working

### ISSUE THREAD

**Issue by jeontwikkeling** [justinhunt/moodle-filter_generico#38]
Hello Justin,

I tried using USER PROFILE VARIABLES - Custom profile field

But it does not seem to be working. Maybe I am doing something wrong?

The example states: User's ice cream preference (custom profile field): @@USER:icecreampref@@

When I use a similar statement using the default profile fields, it works like a charm. When using custom profile fields it displays the statement itself e.g. "@@USER:icecreampref@@". 

I tried adding "profile_field_" and taking out capital letters but that does not have any effect. 

Is this a a bug or am I doing something wrong? :-)

Thanks a lot in advance. 
Joris

**Comment by justinhunt** [comment]
I just tested to make sure, and it is working. It will work as you are doing:
@@USER:icecreampref@@ if the custom profile field key is icecreampref

I think the issue might be that if the field is empty, it just resolves as the variable name, ie: @@USER:icecreampref@@
Which is a bit naff isn't it. I just fixed that and will post it from now

Anyway check that the profile field key is correct AND the logged in user has something in that profile field, and it should work.

**Comment by justinhunt** [comment]
sorry I closed that a bit hasty. Please let me know if its working and then I will close it

**Comment by jeontwikkeling** [comment]
Thank you for your trouble. I got it working now.. don't know what I changed to get it working though. If I find out I'll let you know. The profilefield was not empty, so that was not the problem. 

I do need to use capitals for "USER" though. 

Thanks again!

**Comment by jeontwikkeling** [comment]
After fooling around a little bit more on a identical environment with the original script if found that the profile field key has to be in only lowercase. 

I thought I tested this yesterday, but discovered I changed the wrong value :-)
