### ISSUE TITLE
cannot install or activate plugin

### ISSUE THREAD

**Issue by mbboc** [justinhunt/moodle-filter_generico#4]
Hello 
I get this error when installing. Moodle 3.1.1+ (Build: 20160817)
filter_generico_moodle31_2016082001.zip

Ungültige Admin-Einstellungen ({$a})

Weitere Informationen über diesen Fehler
Debug info:
Error code: invalidadminsettingname
Stack trace:

    line 1699 of /lib/adminlib.php: moodle_exception thrown
    line 1565 of /lib/adminlib.php: call to admin_setting->parse_setting_name()
    line 255 of /filter/generico/locallib.php: call to admin_setting->__construct()
    line 32 of /filter/generico/db/install.php: call to admin_setting_genericopresets->__construct()
    line 525 of /lib/upgradelib.php: call to xmldb_filter_generico_install()
    line 1742 of /lib/upgradelib.php: call to upgrade_plugins()
    line 683 of /admin/index.php: call to upgrade_noncore()

**Comment by justinhunt** [comment]
Thanks for posting this. I think I have fixed it now. It was great to have the bug report.
