### ISSUE TITLE
filter breaks behat 

### ISSUE THREAD

**Issue by ewallah** [justinhunt/moodle-filter_generico#5]
-->filter_generico

!!! Exception - Warning: Missing argument 1 for admin_setting_genericopresets::__construct(), called in [dirroot]/filter/generico/db/install.php on line 32 and defined in [dirroot]/filter/generico/locallib.php on line 249 !!!
!!
Error code: generalexceptionmessage !!
!! Stack trace: * line 158 of /lib/behat/lib.php: Exception thrown
* line 249 of /filter/generico/locallib.php: call to behat_error_handler()
* line 32 of /filter/generico/db/install.php: call to admin_setting_genericopresets-&gt;__construct()
* line 525 of /lib/upgradelib.php: call to xmldb_filter_generico_install()
* line 1742 of /lib/upgradelib.php: call to upgrade_plugins()
* line 491 of /lib/installlib.php: call to upgrade_noncore()
* line 86 of /lib/behat/classes/util.php: call to install_cli_database()
* line 146 of /admin/tool/behat/cli/util_single_run.php: call to behat_util::install_site()
 !!

**Comment by justinhunt** [comment]
Thanks for the report. Actually there were a number of bugs related to this. i think this was fixed in this commit:
 https://github.com/justinhunt/moodle-filter_generico/commit/f187c8537e6fdfea298cf2484b6a1cf236c2f8b3, 
but there were a few problems after that too. it should be ok now.
