### ISSUE TITLE
formatted_toggle not working in Moodle 3.2.1

### ISSUE THREAD

**Issue by hartmut1s** [justinhunt/moodle-filter_generico#8]
Hi Justin,

I tested the Generico filter. Userfirstname is working, but formatted_toggle isn't. There is no debug message. When I switch AMD to "No," the cursor jumps but the text is not visible. The toggle doesn't function. I purged all caches in my test site but it still doesn't work.

With kind regards,
Hartmut

**Comment by justinhunt** [comment]
Thanks for reporting this. I noticed this just the other day too. It might be related to the theme you/I were using. Was it boost?

**Comment by hartmut1s** [comment]
I used Fordson version 1.2.5. Afterwards I tested formatted_toggle in Boost. My Moodle version is 3.2 (Build: 20161205).

**Comment by hartmut1s** [comment]
Your suspicion is correct. In Moodle 3.2, formatted_toggle doesn't work in Boost or Fordson, but it still does work in Clean. So probably bootstrap 4 affects formatted_toggle.
