### ISSUE TITLE
Ability to add revision to included CSS

### ISSUE THREAD

**Issue by agrowe** [justinhunt/moodle-filter_generico#9]
On pages that have custom CSS loaded with the filter, it adds URLs like the below to the page

```
filter/generico/genericocss.php?t=36
```

Is it possible to add a template revision key to the database so that when they are updated it increments or uses `time()`, then that is appended to the URL like the below

```
filter/generico/genericocss.php?t=36&rev=123
```

This will allow the generated CSS to be cached and remove extra PHP requests from each page load.

I'm not sure if the same is done for JS, but if so, similar could be added there.

Thanks

**Comment by justinhunt** [comment]
Yes. we can do that i think. we need to put a version on each template
anyway. so we could append the version to the url for custom css.

javascript gets pretty complicated internally but with any luck that can be
done Similarly

2017/03/21 午前7:59 "agrowe" <notifications@github.com>:

**Comment by agrowe** [comment]
An example on my fork is here. I tested it locally and it checks out ok

https://github.com/agrowe/moodle-filter_generico/commit/af0c891f937a2874bb6b69d77332cd08eea5e4e6

**Comment by agrowe** [comment]
Hi Justin,

What are your thoughts on this if I submit a pull request to your repo?

**Comment by justinhunt** [comment]
Actually I pulled it yesterday
https://github.com/justinhunt/moodle-filter_generico/pull/10
Sorry I should have mentioned that here. Really appreciate it. Thanks
